Repository uit-cosmo/cosmoplots, pull requests merged in 2022-02, with the labels that each got.

#2 Fix log axis base
  cosmoplots/__init__.py
  cosmoplots/axes.py
Labels: enhancement

#3 Add Use section in Readme file
  README.md
  pyproject.toml
Labels: documentation

#4 Log axes example
  README.md
  cosmoplots/__init__.py
  cosmoplots/axes.py
  pyproject.toml
  setup.py
Labels: bug, documentation

#8 Add workflow to automate release to PyPI
  .github/release-drafter.yml
  .github/workflows/release.yml
  cosmoplots/__init__.py
  pyproject.toml
  setup.py
Labels: documentation
